# def __init__(self, name, subclass=None, super=None, aspect=None, weapon=None):
class Armor:
    def __init__(self, name, subclass=None, super=None, aspect=None, weapon=None):
        self.name = name
        self.subclass = subclass
        self.super = super
        self.aspect = aspect
        self.weapon = weapon

armor = {
    "Titan": [
        Armor("Praxic Vestment"),
        Armor("Melas Panoplia", "Solar"),
        Armor("Blastwave Striders"),
        Armor("Wishful Ignorance", ("Strand", "Prismatic")),
        Armor("Hazardous Propulsion"),
        Armor("Stoicism", "Prismatic"),
        Armor("Pyrogale Gauntlets", "Solar", "Burning Maul"),
        Armor("Arbor Warden"),
        Armor("Cadmus Ridge Lancecap", ("Stasis", "Prismatic"), "Glacial Quake"),
        Armor("Abeyant Leap"),
        Armor("Point-Contact Cannon Brace", ("Arc", "Prismatic")),
        Armor("Second Chance", ("Void", "Prismatic")),
        Armor("Loreley Splendor Helm", ("Solar, Prismatic"), "Hammer of Sol"),
        Armor("Hoarfrost-Z", ("Stasis", "Prismatic"), "Glacial Quake"),
        Armor("No Backup Plans"),
        Armor("The Path of Burning Steps"),
        Armor("Cuirass of the Falling Star"),
        Armor("Precious Scars"),
        Armor("Icefall Mantle", ("Stasis", "Prismatic"), "Glacial Quake"),
        Armor("Citan\'s Ramparts"),
        Armor("Severance Enclosure"),
        Armor("An Insurmountable Skullfort", ("Arc", "Prismatic")),
        Armor("Eternal Warrior"),
        Armor("Helm of Saint-14", "Void", ("Ward of Dawn", "Sentinel Shield")),
        Armor("Khepri's Horn"),
        Armor("Mask of the Quiet One"),
        Armor("One-Eyed Mask"),
        Armor("ACD/0 Feedack Fence"),
        Armor("Aeon Safe"),
        Armor("Ashen Wake", "Solar"),
        Armor("Doom Fang Pauldron"),
        Armor("Stronghold"),
        Armor("Synthoceps"),
        Armor("Ursa Furiosa", "Void", "Sentinel Shield"),
        Armor("Wormgod Caress"),
        Armor("Actium War Rig", None, None, None, ("Machine Gun", "Auto Rifle")),
        Armor("Armamentarium"),
        Armor("Crest of Alpha Lupi"),
        Armor("Hallowfire Heart"),
        Armor("Heart of Inmost Light"),
        Armor("Antaeus Wards"),
        Armor("Dumemarchers"),
        Armor("Peregrine Greaves", ("Solar", "Arc", "Void", "Prismatic")),
        Armor("Phoenix Cradle"),
        Armor("Lion Rampant"),
        Armor("Mk. 44 Stand Asides"),
        Armor("Peacekeepers", None, None, None, "Submachine Gun")
    ],
    "Hunter": [
        Armor("Fortune's Favor"),
        Armor("Moirai", ("Strand", "Prismatic")),
        Armor("Mask of Fealty", ("Stasis", "Prismatic")),
        Armor("Gifted Conviction"),
        Armor("Balance of Power", ("Strand", "Prismatic"), None, "Threaded Specter"),
        Armor("Relativism", "Prismatic"),
        Armor("Mothkeeper's Wraps"),
        Armor("Triton Vice", None, None, None, "Glaive"),
        Armor("Cyrtarachne\'s Facade"),
        Armor("Speedloader Slacks"),
        Armor("Gyrfalcon's Hauberk"),
        Armor("Caliban\'s Hand", "Solar"),
        Armor("Blight Ranger", "Arc", "Arc Staff"),
        Armor("Renewal Grasps", ("Prismatic", "Stasis")),
        Armor("Radiant Dance Machines"),
        Armor("Star-Eater Scales"),
        Armor("Omnioculus"),
        Armor("Mask of Bakris", ("Arc", "Stasis")),
        Armor("Athrys\'s Embrace", "Solar"),
        Armor("Raiju\'s Harness", "Arc", "Gathering Storm"),
        Armor("The Bombardiers"),
        Armor("Assassin\'s Cowl"),
        Armor("Celestial Nighthawk", ("Solar", "Prismatic"), "Marksman"),
        Armor("Foetracer"),
        Armor("Graviton Forfeit"),
        Armor("Knucklehead Radar"),
        Armor("Wormhusk Crown"),
        Armor("Aeon Swift"),
        Armor("Khepri\'s Sting"),
        Armor("Liar's Handshake", ("Prismatic", "Arc")),
        Armor("Mechaneer\'s Tricksleeves", None, None, None, "Sidearm"),
        Armor("Oathkeeper", None, None, None, "Bow"),
        Armor("Sealed Ahamkara Grasps"),
        Armor("Shards of Galanor", ("Solar", "Prismatic")),
        Armor("Shinobu\'s Vow", "Arc"),
        Armor("Young Ahamkara\'s Spine", "Solar"),
        Armor("Gwisin Vest"),
        Armor("Lucky Raspberry", ("Arc", "Prismatic")),
        Armor("Ophida Spathe", ("Solar", "Prismatic")),
        Armor("Raiden Flux", "Arc", "Arc Staff"),
        Armor("The Dragon\'s Shadow"),
        Armor("The Sixth Coyote"),
        Armor("Fr0st-EE5"),
        Armor("Gemini Jester"),
        Armor("Lucky Pants", None, None, None, "Hand Cannon"),
        Armor("Orpheus Rig", ("Void", "Prismatic"), "Deadfall"),
        Armor("St0mp-EE5")
    ],
    "Warlock": [
        Armor("Deimosuffusion", ("Strand", "Prismatic"), "Needlestorm"),
        Armor("Eunoia", ("Solar", "Prismatic"), None, "Hellion"),
        Armor("Rime-Coat Raiment", ("Prismatic", "Stasis"), None, "Bleak Watcher"),
        Armor("Speaker's Sight", ("Prismatic", "Solar")),
        Armor("Mataiodoxia", ("Strand", "Prismatic")),
        Armor("Solipsism", "Prismatic"),
        Armor("Briarbinds", "Void"),
        Armor("Cenotaph Mask", None, None, None, "Trace Rifle"),
        Armor("Ballidorse Wrathweavers", ("Stasis", "Prismatic"), "Winter\'s Wrath"),
        Armor("Swarmers"),
        Armor("Fallen Sunstar", "Arc"),
        Armor("Rain of Fire"),
        Armor("Osmiomancy Gloves", ("Stasis", "Prismatic")),
        Armor("Secant Filaments"),
        Armor("Nothing Manacles", "Void"),
        Armor("Boots of the Assembler"),
        Armor("Mantle of Battle Harmony"),
        Armor("Dawn Chorus"),
        Armor("Necrotic Grip"),
        Armor("Felwinter\'s Helm"),
        Armor("Promethium Spur"),
        Armor("Apotheosis Veil"),
        Armor("Astrocyte Verse", ("Void", "Prismatic")),
        Armor("Crown of Tempests", ("Arc", "Prismatic")),
        Armor("Eye of Another World"),
        Armor("Nezarec\'s Sin"),
        Armor("Skull of Dire Ahamkara"),
        Armor("The Stag"),
        Armor("Verity's Brow"),
        Armor("Aeon Soul"),
        Armor("Claws of Ahamkara"),
        Armor("Contraverse Hold", ("Void", "Prismatic")),
        Armor("Getaway Artist", ("Arc", "Prismatic")),
        Armor("Karnstein Armlets"),
        Armor("Ophidian Aspect"),
        Armor("Sunbracers", "Solar"),
        Armor("Winter\'s Guile"),
        Armor("Chromatic Fire"),
        Armor("Phoenix Protocol", "Solar", "Well of Radiance"),
        Armor("Sanguine Alchemy"),
        Armor("Starfire Protocol", "Solar"),
        Armor("Stormdancer\'s Brace", ("Arc", "Prismatic"), "Stormtrance"),
        Armor("Vesper of Radius"),
        Armor("Wings of Sacred Dawn"),
        Armor("Geomag Stabilizers"),
        Armor("Lunafaction Boots"),
        Armor("Transversive Steps")
    ]
}